version: '3'

services:
  appointments-db:
    image: postgres:latest
    container_name: appointments-db
    networks:
      - gateway-network
    environment:
      - POSTGRES_DB=appointments_db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=pass
    ports:
      - "5432:5432"

networks:
  gateway-network:
    driver: bridge